package main

import (
	"regexp"
	"strconv"
	"strings"
	"testing"
)

func TestBuildTeXSourceIncludesMathPackages(t *testing.T) {
	source := buildTeXSource("tikzcd", `\begin{tikzcd}A \arrow[r, "\overset{\text{def}}{=}"] & \mathscr S\end{tikzcd}`, false)

	if !strings.Contains(source, `\usepackage{amsmath,amssymb,mathrsfs,tikz,tikz-cd}`) {
		t.Fatalf("expected math packages in wrapper, got:\n%s", source)
	}
	if !strings.Contains(source, `\mathscr`) {
		t.Fatalf("expected projective-morphism diagram source to be preserved, got:\n%s", source)
	}
}

func TestBuildTeXSourceLoadsStandardProjectTikzLibraries(t *testing.T) {
	source := buildTeXSource("tikzpicture", `\begin{tikzpicture}\draw (0,0) -- ($(0,0) + (1,1)$);\end{tikzpicture}`, false)

	if !strings.Contains(source, `\usetikzlibrary{calc,positioning,arrows.meta}`) {
		t.Fatalf("expected standard project TikZ libraries in wrapper, got:\n%s", source)
	}
}

func TestBuildTeXSourceWrapsMathFallback(t *testing.T) {
	source := buildTeXSource("math", `\[\ket{x}=\definitelyunsupportedcommand{x}\]`, false)

	for _, expected := range []string{
		`\usepackage{amsmath,amssymb,mathtools,bm,graphicx,xcolor}`,
		`\providecommand{\ket}`,
		`\providecommand{\norm}`,
		`\providecommand{\xlongequal}`,
		`\[\ket{x}=\definitelyunsupportedcommand{x}\]`,
	} {
		if !strings.Contains(source, expected) {
			t.Fatalf("expected math wrapper to contain %q, got:\n%s", expected, source)
		}
	}
}

func TestNormalizeDiagramSourceWrapsMathDisplayAndInline(t *testing.T) {
	display := normalizeDiagramSource("math", "display", `x+y`, "")
	inline := normalizeDiagramSource("math", "inline", `x+y`, "")
	displayFromSource := normalizeDiagramSource("math", "display", "", `\mathcal{M}`)
	inlineFromSource := normalizeDiagramSource("math", "inline", "", `\cos \theta`)

	if display != `\[x+y\]` {
		t.Fatalf("expected display math wrapper, got %q", display)
	}
	if inline != `\(x+y\)` {
		t.Fatalf("expected inline math wrapper, got %q", inline)
	}
	if displayFromSource != `\[\mathcal{M}\]` {
		t.Fatalf("expected display math wrapper from source, got %q", displayFromSource)
	}
	if inlineFromSource != `\(\cos \theta\)` {
		t.Fatalf("expected inline math wrapper from source, got %q", inlineFromSource)
	}
}

func TestTightenRenderedSVGCropsDvisvgmPageCanvas(t *testing.T) {
	source := `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -792 612 792" height="792pt" version="1.1" width="612pt"><g id="page1"><g transform="matrix(1 0 0 -1 0 0)"><path d="M29.742187 683.648465L83.1406 737.043" fill="none" stroke="#000" stroke-width=".79701"/><path d="M114.780869 655.300349L171.476283 711.991788" fill="none" stroke="#000" stroke-width=".79701"/></g></g></svg>`

	got := tightenRenderedSVG(source)
	if strings.Contains(got, `viewBox="0 -792 612 792"`) || strings.Contains(got, `height="792pt"`) || strings.Contains(got, `width="612pt"`) {
		t.Fatalf("expected page-sized SVG attributes to be tightened, got %s", got)
	}
	viewBox := regexp.MustCompile(`viewBox="([^"]+)"`).FindStringSubmatch(got)
	if len(viewBox) < 2 {
		t.Fatalf("expected tightened SVG to keep a viewBox, got %s", got)
	}
	fields := strings.Fields(viewBox[1])
	if len(fields) != 4 {
		t.Fatalf("expected four viewBox fields, got %q", viewBox[1])
	}
	width, err := strconv.ParseFloat(fields[2], 64)
	if err != nil {
		t.Fatalf("parse width: %v", err)
	}
	height, err := strconv.ParseFloat(fields[3], 64)
	if err != nil {
		t.Fatalf("parse height: %v", err)
	}
	if width >= 220 || height >= 100 {
		t.Fatalf("expected tight bounds, got viewBox %q in SVG %s", viewBox[1], got)
	}
}

func TestTightenRenderedSVGCropsDvisvgmXMLDocument(t *testing.T) {
	source := `<?xml version='1.0' encoding='UTF-8'?>
<!-- This file was generated by dvisvgm 3.0.3 -->
<svg version='1.1' xmlns='http://www.w3.org/2000/svg' width='612pt' height='792pt' viewBox='0 -792 612 792'>
<g id='page1'>
<g transform='matrix(1 0 0 -1 0 0)'>
<path d='M29.742189 712.390657L86.4375 740.7383' stroke='#000' fill='none' stroke-width='.3985'/>
</g>
</g>
</svg>`

	got := tightenRenderedSVG(source)
	if !strings.Contains(got, `<?xml version='1.0'`) {
		t.Fatalf("expected XML declaration to be preserved, got %s", got)
	}
	if strings.Contains(got, `viewBox='0 -792 612 792'`) || strings.Contains(got, `height='792pt'`) || strings.Contains(got, `width='612pt'`) {
		t.Fatalf("expected single-quoted page-sized SVG attributes to be tightened, got %s", got)
	}
	viewBox := regexp.MustCompile(`viewBox="([^"]+)"`).FindStringSubmatch(got)
	if len(viewBox) < 2 {
		t.Fatalf("expected tightened SVG to rewrite viewBox with double quotes, got %s", got)
	}
	fields := strings.Fields(viewBox[1])
	if len(fields) != 4 {
		t.Fatalf("expected four viewBox fields, got %q", viewBox[1])
	}
	width, err := strconv.ParseFloat(fields[2], 64)
	if err != nil {
		t.Fatalf("parse width: %v", err)
	}
	height, err := strconv.ParseFloat(fields[3], 64)
	if err != nil {
		t.Fatalf("parse height: %v", err)
	}
	if width >= 80 || height >= 40 {
		t.Fatalf("expected XML document SVG to be tightly cropped, got viewBox %q in SVG %s", viewBox[1], got)
	}
}

func TestTightenRenderedSVGParsesPathCommandsAndDefinitions(t *testing.T) {
	source := `<svg viewBox="0 0 612 792" height="792pt" width="612pt"><defs><path id="tick" d="M0 0H12V8"/></defs><g transform="translate(30 40)"><path d="M10 20h40v30c10 0 20 10 30 20" stroke="#000" fill="none"/><use href="#tick" x="120" y="140"/></g></svg>`

	got := tightenRenderedSVG(source)
	viewBox := regexp.MustCompile(`viewBox="([^"]+)"`).FindStringSubmatch(got)
	if len(viewBox) < 2 {
		t.Fatalf("expected tightened SVG to keep a viewBox, got %s", got)
	}
	fields := strings.Fields(viewBox[1])
	if len(fields) != 4 {
		t.Fatalf("expected four viewBox fields, got %q", viewBox[1])
	}
	width, err := strconv.ParseFloat(fields[2], 64)
	if err != nil {
		t.Fatalf("parse width: %v", err)
	}
	height, err := strconv.ParseFloat(fields[3], 64)
	if err != nil {
		t.Fatalf("parse height: %v", err)
	}
	if width >= 180 || height >= 180 {
		t.Fatalf("expected path-command bounds to stay tight, got viewBox %q in SVG %s", viewBox[1], got)
	}
}

func TestTightenRenderedSVGKeepsSingleHorizontalLine(t *testing.T) {
	source := `<svg viewBox="0 0 612 792" height="792pt" width="612pt"><path d="M10 20H110" stroke="#000" fill="none"/></svg>`

	got := tightenRenderedSVG(source)
	viewBox := regexp.MustCompile(`viewBox="([^"]+)"`).FindStringSubmatch(got)
	if len(viewBox) < 2 {
		t.Fatalf("expected tightened SVG to keep a viewBox, got %s", got)
	}
	fields := strings.Fields(viewBox[1])
	if len(fields) != 4 {
		t.Fatalf("expected four viewBox fields, got %q", viewBox[1])
	}
	height, err := strconv.ParseFloat(fields[3], 64)
	if err != nil {
		t.Fatalf("parse height: %v", err)
	}
	if height <= 0 || height > 3 {
		t.Fatalf("expected padded non-zero line height, got viewBox %q in SVG %s", viewBox[1], got)
	}
}
