package typstadapter

import (
	"encoding/base64"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/rinspacehq/rinspace-renderer/api/internal/mathrender"
)

func TestAdaptHTMLKeepsChapterBoundaryAndCrossPageReferences(t *testing.T) {
	source := `<!doctype html><html><head><style>body{color:red}</style></head><body>` +
		`<p><span id="rin-page-second"></span></p><h2>第二章</h2><p>第二章正文</p>` +
		`<p><span id="rin-page-group-theory"></span></p><h2 id="group-theory">第四章</h2>` +
		`<p>第四章正文 <a href="#definition">前文定义</a></p>` +
		`<p><span id="rin-page-definition"></span></p><h3 id="definition">定义</h3>` +
		`<p><a href="#group-theory">返回第四章</a></p></body></html>`
	result, err := AdaptHTML([]byte(source), "book", nil)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Pages) != 3 || result.Pages[1].ID != "group-theory" || result.Pages[1].Title != "第四章" ||
		strings.Contains(result.Pages[1].HTML, "第二章正文") || !strings.Contains(result.Pages[1].HTML, "第四章正文") ||
		!strings.Contains(result.Pages[1].HTML, `class="rin-reader-ref"`) ||
		!strings.Contains(result.Pages[0].HTML, `id="second"`) {
		t.Fatalf("incorrect Typst book pages: %#v", result.Pages)
	}
}

// The compiler corpus is generated by the pinned experiment and intentionally
// kept out of Git. Set RIN_TYPST_CORPUS_OUTPUT_DIR to exercise the real output.
func TestPinnedCompilerCorpus(t *testing.T) {
	directory := os.Getenv("RIN_TYPST_CORPUS_OUTPUT_DIR")
	if directory == "" {
		t.Skip("pinned compiler corpus output is not configured")
	}
	book, err := os.ReadFile(filepath.Join(directory, "book.html"))
	if err != nil {
		t.Fatal(err)
	}
	bookResult, err := AdaptHTML(book, "book", nil)
	if err != nil {
		t.Fatal(err)
	}
	if len(bookResult.Pages) != 9 || bookResult.Pages[6].ID != "group-theory" ||
		!strings.Contains(bookResult.Pages[6].HTML, "本章引言必须") ||
		strings.Contains(bookResult.Pages[6].HTML, "本章没有 section") {
		t.Fatalf("pinned Typst book pagination drift: %#v", bookResult.Pages)
	}
	blog, err := os.ReadFile(filepath.Join(directory, "blog.html"))
	if err != nil {
		t.Fatal(err)
	}
	svg, err := os.ReadFile(filepath.Join("..", "..", "..", "corpus", "fixtures", "typst", "blog", "diagram.svg"))
	if err != nil {
		t.Fatal(err)
	}
	blogResult, err := AdaptHTML(blog, "article", map[string][]byte{"diagram.svg": svg})
	if err != nil {
		t.Fatal(err)
	}
	if len(blogResult.Pages) != 1 || len(blogResult.Assets) != 1 || !strings.Contains(blogResult.Pages[0].HTML, "<math>") {
		t.Fatalf("pinned Typst blog lost semantic content: %#v", blogResult)
	}
	renderer := mathrender.NewMathJaxRenderer("../../../engines/mathjax/render-mathjax.mjs", 10*time.Second, 32<<10)
	for label, native := range map[string]Result{"blog": blogResult, "book": bookResult} {
		start := time.Now()
		mathjax, err := RenderMathML(t.Context(), native, renderer)
		if err != nil {
			t.Fatalf("%s MathJax alternative failed: %v", label, err)
		}
		t.Logf("%s: native fragment bytes=%d, MathJax fragment bytes=%d, conversion=%s", label,
			pageBytes(native.Pages), pageBytes(mathjax.Pages), time.Since(start))
	}
}

func pageBytes(pages []Page) int {
	total := 0
	for _, page := range pages {
		total += len(page.HTML)
	}
	return total
}

func TestAdaptHTMLMapsEmbeddedImageToExactProjectAsset(t *testing.T) {
	asset := []byte(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1 1"><rect width="1" height="1"/></svg>`)
	source := `<html><body><h2>Article</h2><p><img src="data:image/svg+xml;base64,` +
		base64.StdEncoding.EncodeToString(asset) + `" style="width: 25%"></p></body></html>`
	result, err := AdaptHTML([]byte(source), "article", map[string][]byte{"assets/figure.svg": asset})
	if err != nil {
		t.Fatal(err)
	}
	if len(result.AssetPaths) != 1 || !strings.HasPrefix(result.AssetPaths[0], "typst-assets/") ||
		len(result.Assets) != 1 || result.Assets[0].SourcePath != "assets/figure.svg" ||
		!strings.Contains(result.Pages[0].HTML, `data-rin-asset-path="typst-assets/`) ||
		strings.Contains(result.Pages[0].HTML, "data:image") {
		t.Fatalf("embedded image was not mapped to a declared source asset: %#v", result)
	}
}

func TestAdaptHTMLPublishesCompilerGeneratedSVG(t *testing.T) {
	generated := []byte(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10"><path d="M0 0L10 10" stroke="black"/></svg>`)
	source := `<html><body><h2>Article</h2><img src="data:image/svg+xml;base64,` +
		base64.StdEncoding.EncodeToString(generated) + `"></body></html>`
	result, err := AdaptHTML([]byte(source), "article", nil)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Assets) != 1 || result.Assets[0].SourcePath != "" ||
		!strings.HasPrefix(result.Assets[0].Path, "typst-assets/") ||
		!strings.Contains(result.Pages[0].HTML, `data-rin-asset-path="typst-assets/`) ||
		strings.Contains(result.Pages[0].HTML, "data:image") {
		t.Fatalf("compiler-generated SVG was not made into a declared asset: %#v", result)
	}
}

func TestAdaptHTMLPublishesInlineSVGAsSanitizedAsset(t *testing.T) {
	source := `<html><body><h2>Drawing</h2><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10"><script>alert(1)</script><path d="M0 0L10 10" stroke="black"/></svg></body></html>`
	result, err := AdaptHTML([]byte(source), "article", nil)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Assets) != 1 || result.Assets[0].SourcePath != "" ||
		!strings.Contains(result.Pages[0].HTML, `data-rin-asset-path="typst-assets/`) ||
		strings.Contains(result.Pages[0].HTML, "<svg") ||
		strings.Contains(string(result.Assets[0].Body), "script") {
		t.Fatalf("inline Typst SVG was not normalized as an independent asset: %#v", result)
	}
}

// The fragments below are verbatim output of the pinned Typst HTML backend. It
// writes MathML presentation attributes so MathJax can reproduce the compiler's
// native spacing, operator form, stretching, accents and fraction rules.
func TestAdaptHTMLKeepsPinnedMathMLPresentationAttributes(t *testing.T) {
	source := `<!doctype html><html><head><style>mtd{}</style></head><body>` +
		`<h2>公式</h2>` +
		`<p><math><msubsup><mo lspace="0em">∫</mo><mn>0</mn><mn>1</mn></msubsup><msup><mi>𝑥</mi><mn>2</mn></msup>` +
		`<mspace width="0.1667em"/><mo form="prefix" lspace="0em" rspace="0em">d</mo><mi>𝑥</mi></math></p>` +
		`<math display="block"><mo lspace="0.2222222222222222em" rspace="0.2222222222222222em">⋅</mo>` +
		`<mrow><mo>|</mo><mi>𝑥</mi><mo stretchy="false">|</mo></mrow>` +
		`<mover accent="true"><mi>𝑥</mi><mo>̂</mo></mover>` +
		`<munder accentunder="true"><mrow><mn>1</mn></mrow><mo>⏟</mo></munder>` +
		`<mi mathvariant="normal">d</mi>` +
		`<mfrac linethickness="0"><mi>𝑛</mi><mi>𝑘</mi></mfrac></math>` +
		`</body></html>`
	result, err := AdaptHTML([]byte(source), "article", nil)
	if err != nil {
		t.Fatal(err)
	}
	page := result.Pages[0].HTML
	for _, fragment := range []string{
		`<mo lspace="0em">`, `form="prefix"`, `lspace="0.2222222222222222em"`, `rspace="0.2222222222222222em"`,
		`stretchy="false"`, `accent="true"`, `accentunder="true"`, `mathvariant="normal"`,
		`linethickness="0"`, `mspace width="0.1667em"`,
	} {
		if !strings.Contains(page, fragment) {
			t.Fatalf("pinned Typst MathML attribute %q was not preserved: %s", fragment, page)
		}
	}
	if strings.Contains(page, "style=") {
		t.Fatalf("Native Typst CSS leaked into the reader fragment: %s", page)
	}
}

// Verbatim output of the pinned Typst HTML backend for the live article a/363,
// whose body is a matrix formula followed by a table-built commutative
// diagram. Both shapes must keep their math semantics in the reader fragment.
func TestAdaptHTMLKeepsRealArticleMathAndCommutativeDiagram(t *testing.T) {
	matrix := `<math display="block"><mi>𝐴</mi><mo>=</mo><mrow><mo>(</mo><mtable>` +
		`<mtr><mtd><mn>1</mn></mtd><mtd><mn>2</mn></mtd></mtr>` +
		`<mtr><mtd><mn>3</mn></mtd><mtd><mn>4</mn></mtd></mtr>` +
		`</mtable><mo>)</mo></mrow><mo rspace="0em">,</mo><mspace width="1em"/>` +
		`<msup><mi>𝐴</mi><mrow><mo>−</mo><mn>1</mn></mrow></msup><mo>=</mo>` +
		`<mfrac><mn>1</mn><mrow><mo lspace="0em" rspace="0em">det</mo>` +
		`<mrow><mo>(</mo><mi>𝐴</mi><mo>)</mo></mrow></mrow></mfrac>` +
		`<mrow><mo>(</mo><mtable><mtr><mtd><mi>𝑑</mi></mtd><mtd><mo>−</mo><mi>𝑏</mi></mtd></mtr>` +
		`<mtr><mtd><mo>−</mo><mi>𝑐</mi></mtd><mtd><mi>𝑎</mi></mtd></mtr></mtable><mo>)</mo></mrow></math>`
	diagram := `<figure><table>` +
		`<tr><td><math><mi>𝐴</mi></math></td>` +
		`<td><math><mo lspace="0em" rspace="0em" stretchy="false">→</mo></math></td>` +
		`<td><math><mi>𝐵</mi></math></td></tr>` +
		`<tr><td></td>` +
		`<td><math><mo lspace="0em" rspace="0em" stretchy="false">↓</mo></math></td>` +
		`<td></td></tr>` +
		`<tr><td><math><mi>𝐶</mi></math></td>` +
		`<td><math><mo lspace="0em" rspace="0em" stretchy="false">→</mo></math></td>` +
		`<td><math><mi>𝐷</mi></math></td></tr></table>` +
		"<figcaption>表\u00a01\u2003交换图：表格与数学排版</figcaption></figure>"
	source := `<!doctype html><html><head><style>mtd{}</style></head><body>` +
		`<p><span id="rin-page-introduction"></span></p><h2>1. 引言</h2>` +
		`<p>行间公式：</p>` + matrix + `<p>交换图：</p>` + diagram + `</body></html>`
	result, err := AdaptHTML([]byte(source), "article", nil)
	if err != nil {
		t.Fatalf("real a/363 formula and commutative diagram were rejected: %v", err)
	}
	page := result.Pages[0].HTML
	for _, fragment := range []string{
		`<mfrac>`, `<msup>`, `<mspace width="1em">`,
		`<mo lspace="0em" rspace="0em" stretchy="false">`, `<figure>`, `<figcaption>`,
	} {
		if !strings.Contains(page, fragment) {
			t.Fatalf("real a/363 fragment %q was dropped: %s", fragment, page)
		}
	}
	if got := strings.Count(page, `<mtable>`); got != 2 {
		t.Fatalf("real a/363 matrices were dropped: want 2 mtable, got %d: %s", got, page)
	}
	if got := strings.Count(page, `<math>`); got != 7 {
		t.Fatalf("real a/363 commutative diagram cells were dropped: want 7 inline math, got %d: %s", got, page)
	}
	if strings.Contains(page, "style=") {
		t.Fatalf("Native Typst CSS leaked into the reader fragment: %s", page)
	}
}

func TestAdaptHTMLRejectsUnpinnedMathMLAttributes(t *testing.T) {
	for _, source := range []string{
		`<html><body><h2>Math</h2><p lspace="1em">block</p></body></html>`,
		`<html><body><h2>Math</h2><math><mo lspace="expression(alert(1))">x</mo></math></body></html>`,
		`<html><body><h2>Math</h2><math><mo lspace="url(1em)">x</mo></math></body></html>`,
		`<html><body><h2>Math</h2><math><mo form="weird">x</mo></math></body></html>`,
		`<html><body><h2>Math</h2><math><mo stretchy="maybe">x</mo></math></body></html>`,
		`<html><body><h2>Math</h2><math><mi stretchy="true">x</mi></math></body></html>`,
		`<html><body><h2>Math</h2><math><mover accent="yes"><mi>x</mi></mover></math></body></html>`,
		`<html><body><h2>Math</h2><math><mfrac accent="true"><mi>x</mi></mfrac></math></body></html>`,
		`<html><body><h2>Math</h2><math><munder accentunder="1"><mi>x</mi></munder></math></body></html>`,
		`<html><body><h2>Math</h2><math><mi mathvariant="evil">x</mi></math></body></html>`,
		`<html><body><h2>Math</h2><math><mfrac mathvariant="normal"><mi>x</mi></mfrac></math></body></html>`,
		`<html><body><h2>Math</h2><math><mfrac linethickness="url(x)"><mi>x</mi></mfrac></math></body></html>`,
		`<html><body><h2>Math</h2><math><mo linethickness="1px">x</mo></math></body></html>`,
		`<html><body><h2>Math</h2><math><mspace width="1em" onload="alert(1)"/></math></body></html>`,
	} {
		if _, err := AdaptHTML([]byte(source), "article", nil); err == nil {
			t.Fatalf("unpinned Typst MathML attribute was accepted: %s", source)
		}
	}
}

func TestAdaptHTMLRejectsUnsafeAndAmbiguousOutput(t *testing.T) {
	for _, source := range []string{
		`<html><body><script>alert(1)</script></body></html>`,
		`<html><body><p><span id="rin-page-a"></span></p><h2>A</h2><p><span id="rin-page-a"></span></p><h2>B</h2></body></html>`,
		`<html><body><p>Preface without marker</p><p><span id="rin-page-a"></span></p><h2>A</h2></body></html>`,
		`<html><body><p><span id="rin-page-a"></span></p><h2>A</h2><p><a href="javascript:alert(1)">bad</a></p></body></html>`,
		`<html><body><p><span id="rin-page-a"></span></p><h2>A</h2><p><span id="rin-page-hidden">B</span></p></body></html>`,
	} {
		if _, err := AdaptHTML([]byte(source), "book", nil); err == nil {
			t.Fatalf("unsafe or ambiguous Typst HTML was accepted: %s", source)
		}
	}
}
