// Package typstadapter converts the pinned Typst compiler's native HTML into
// page fragments. It deliberately does not execute Typst or trust source HTML.
package typstadapter

import (
	"bytes"
	"crypto/sha256"
	"encoding/base64"
	"errors"
	"fmt"
	"io"
	"net/url"
	"regexp"
	"sort"
	"strings"

	"golang.org/x/net/html"
	"golang.org/x/net/html/atom"

	"github.com/rinspacehq/rinspace-renderer/api/internal/contracts"
	"github.com/rinspacehq/rinspace-renderer/api/internal/finaloutput"
	"github.com/rinspacehq/rinspace-renderer/api/internal/renderstorage"
)

const maxNativeHTMLBytes = 32 << 20

var pageMarker = regexp.MustCompile(`^rin-page-([a-z][a-z0-9-]{0,79})$`)
var codeLanguage = regexp.MustCompile(`^[a-zA-Z0-9_+-]{1,32}$`)

// The pinned Typst HTML backend writes MathML presentation attributes so the
// MathJax conversion reproduces the compiler's native spacing and stretching.
// Every value stays bounded and every attribute stays on the element that the
// MathML specification assigns it to; anything else still fails closed.
var mathLength = regexp.MustCompile(`^-?(?:0|[1-9][0-9]{0,8})(?:\.[0-9]{1,20})?(?:em|ex|mu|pt|px|pc|cm|mm|in|%)?$`)
var mathFlag = regexp.MustCompile(`^(?:true|false)$`)
var mathForm = regexp.MustCompile(`^(?:prefix|infix|postfix)$`)
var mathVariant = regexp.MustCompile(`^(?:normal|bold|italic|bold-italic|double-struck|bold-fraktur|fraktur|bold-script|script|bold-sans-serif|sans-serif|sans-serif-italic|sans-serif-bold-italic|monospace|initial|tailed|looped|stretched)$`)

// mathTokenElement reports the MathML token elements that carry a math variant.
func mathTokenElement(tag string) bool {
	switch tag {
	case "mi", "mn", "mo", "ms", "mtext":
		return true
	}
	return false
}

type Page struct {
	ID    string
	Title string
	Level int
	HTML  string
}

type Result struct {
	Pages      []Page
	AssetPaths []string
	Assets     []Asset
}

type Asset struct {
	Path       string
	SourcePath string
	Body       []byte
}

// AdaptHTML requires the complete HTML document from one Typst compilation.
// Book page identities come only from the explicit rinWebPage marker. Every
// image is normalized into a content-addressed asset so the existing upload
// path can replace its URL after the final-output validator checks the fragment.
// SourcePath is retained when Typst embedded an unchanged project SVG; graphics
// generated by Typst itself have no matching project file.
func AdaptHTML(source []byte, mode string, projectFiles map[string][]byte) (Result, error) {
	if len(source) == 0 || len(source) > maxNativeHTMLBytes {
		return Result{}, errors.New("Typst HTML output is empty or too large")
	}
	if mode != "article" && mode != "book" {
		return Result{}, errors.New("Typst document mode is invalid")
	}
	root, err := html.Parse(bytes.NewReader(source))
	if err != nil {
		return Result{}, fmt.Errorf("parse Typst HTML: %w", err)
	}
	body := findElement(root, "body")
	if body == nil {
		return Result{}, errors.New("Typst HTML has no body")
	}
	assets := map[string]Asset{}
	assetHashes := make(map[[32]byte]string)
	fileNames := make([]string, 0, len(projectFiles))
	for name := range projectFiles {
		fileNames = append(fileNames, name)
	}
	sort.Strings(fileNames)
	for _, name := range fileNames {
		body := projectFiles[name]
		if cleaned, ok := contracts.CleanProjectPath(name); ok && cleaned == name && strings.HasSuffix(strings.ToLower(name), ".svg") {
			hash := sha256.Sum256(body)
			if _, exists := assetHashes[hash]; !exists {
				assetHashes[hash] = name
			}
		}
	}
	result := Result{Pages: []Page{}}
	current := Page{ID: "page-main"}
	seenPages := map[string]struct{}{}
	var fragment bytes.Buffer
	flush := func() error {
		if current.ID == "" || strings.TrimSpace(fragment.String()) == "" {
			return errors.New("Typst page has no content")
		}
		current.HTML = fragment.String()
		if mode == "book" && !strings.Contains(current.HTML, `id="`+current.ID+`"`) {
			current.HTML = `<span id="` + current.ID + `"></span>` + current.HTML
		}
		if err := finaloutput.Validate(finaloutput.Input{Adapter: "typst", Fragment: current.HTML, ClientOwnedAssets: assetKeys(assets)}); err != nil {
			return fmt.Errorf("Typst final page %q: %w", current.ID, err)
		}
		result.Pages = append(result.Pages, current)
		fragment.Reset()
		return nil
	}
	for child := body.FirstChild; child != nil; child = child.NextSibling {
		if marker, ok := markerPageID(child); ok {
			if _, duplicate := seenPages[marker]; duplicate {
				return Result{}, fmt.Errorf("duplicate Typst page marker %q", marker)
			}
			seenPages[marker] = struct{}{}
			if mode == "article" {
				// The shared template can mark article sections, but an article
				// remains a single reader page.
				continue
			}
			if len(seenPages) == 1 {
				if strings.TrimSpace(fragment.String()) != "" {
					return Result{}, errors.New("book content precedes its first page marker")
				}
			} else if err := flush(); err != nil {
				return Result{}, err
			}
			current = Page{ID: marker}
			continue
		}
		if mode == "book" && len(seenPages) == 0 {
			if child.Type == html.TextNode && strings.TrimSpace(child.Data) == "" {
				continue
			}
			return Result{}, errors.New("book content precedes its first page marker")
		}
		if err := sanitizeNode(child, assetHashes, assets); err != nil {
			return Result{}, err
		}
		if current.Title == "" && child.Type == html.ElementNode && isHeading(child.Data) {
			current.Title = strings.TrimSpace(textContent(child))
			current.Level = int(child.Data[1] - '0')
		}
		if err := html.Render(&fragment, child); err != nil {
			return Result{}, err
		}
	}
	if mode == "book" && len(seenPages) == 0 {
		return Result{}, errors.New("book HTML has no explicit page marker")
	}
	if err := flush(); err != nil {
		return Result{}, err
	}
	result.AssetPaths = assetKeys(assets)
	for _, path := range result.AssetPaths {
		result.Assets = append(result.Assets, assets[path])
	}
	if mode == "book" {
		// Whole-book pass: page fragments are sanitized, but a reader can only
		// follow cross-chapter references, footnotes and the bibliography when
		// every anchor resolves to exactly one page in the compiled book.
		if err := resolveBookLinks(result.Pages); err != nil {
			return Result{}, err
		}
	}
	return result, nil
}

func markerPageID(node *html.Node) (string, bool) {
	if node.Type != html.ElementNode || node.Data != "p" || node.FirstChild == nil || node.FirstChild != node.LastChild || node.FirstChild.Data != "span" {
		return "", false
	}
	span := node.FirstChild
	if span.FirstChild != nil {
		return "", false
	}
	for _, attr := range span.Attr {
		if attr.Key == "id" {
			match := pageMarker.FindStringSubmatch(attr.Val)
			return matchValue(match), len(match) == 2
		}
	}
	return "", false
}

func matchValue(match []string) string {
	if len(match) == 2 {
		return match[1]
	}
	return ""
}

func sanitizeNode(node *html.Node, assetHashes map[[32]byte]string, assets map[string]Asset) error {
	if node.Type == html.CommentNode || node.Type == html.DoctypeNode {
		return errors.New("Typst body contains non-content markup")
	}
	if node.Type != html.ElementNode {
		return nil
	}
	if node.Data == "svg" {
		var raw bytes.Buffer
		if err := html.Render(&raw, node); err != nil || raw.Len() > 4<<20 {
			return errors.New("Typst inline SVG is invalid or too large")
		}
		path, err := normalizeImage(raw.Bytes(), "", assets)
		if err != nil {
			return err
		}
		node.Data, node.DataAtom = "img", atom.Img
		node.Attr = []html.Attribute{{Key: "src", Val: path}, {Key: "data-rin-asset-path", Val: path}}
		node.FirstChild, node.LastChild = nil, nil
		return nil
	}
	if !allowedElement(node.Data) {
		return fmt.Errorf("Typst HTML element <%s> is unsupported", node.Data)
	}
	attrs := make([]html.Attribute, 0, len(node.Attr)+2)
	seen := map[string]struct{}{}
	internalLink := false
	for _, attr := range node.Attr {
		name := strings.ToLower(attr.Key)
		if attr.Namespace != "" || strings.HasPrefix(name, "on") || strings.HasPrefix(name, "data-") && name != "data-lang" || name == "srcset" {
			return fmt.Errorf("Typst HTML attribute %q is unsafe", name)
		}
		if _, duplicate := seen[name]; duplicate {
			return fmt.Errorf("Typst HTML duplicates attribute %q", name)
		}
		seen[name] = struct{}{}
		switch name {
		case "data-lang":
			if node.Data != "pre" && node.Data != "code" || !codeLanguage.MatchString(attr.Val) {
				return errors.New("Typst code language is invalid")
			}
			attrs = append(attrs, attr)
		case "style": // Native Typst CSS is page-global; reader chrome owns styling.
			continue
		case "display":
			if node.Data != "math" || attr.Val != "block" && attr.Val != "inline" {
				return errors.New("Typst MathML display is invalid")
			}
			attrs = append(attrs, attr)
		case "lspace", "rspace":
			if node.Data != "mo" && node.Data != "mspace" || !mathLength.MatchString(attr.Val) {
				return fmt.Errorf("Typst MathML %s is invalid", name)
			}
			attrs = append(attrs, attr)
		case "form":
			if node.Data != "mo" || !mathForm.MatchString(attr.Val) {
				return errors.New("Typst MathML operator form is invalid")
			}
			attrs = append(attrs, attr)
		case "stretchy":
			if node.Data != "mo" || !mathFlag.MatchString(attr.Val) {
				return errors.New("Typst MathML operator stretching is invalid")
			}
			attrs = append(attrs, attr)
		case "accent":
			if node.Data != "mover" || !mathFlag.MatchString(attr.Val) {
				return errors.New("Typst MathML accent is invalid")
			}
			attrs = append(attrs, attr)
		case "accentunder":
			if node.Data != "munder" || !mathFlag.MatchString(attr.Val) {
				return errors.New("Typst MathML under-accent is invalid")
			}
			attrs = append(attrs, attr)
		case "linethickness":
			if node.Data != "mfrac" || !mathLength.MatchString(attr.Val) {
				return errors.New("Typst MathML fraction rule is invalid")
			}
			attrs = append(attrs, attr)
		case "mathvariant":
			if !mathTokenElement(node.Data) || !mathVariant.MatchString(attr.Val) {
				return errors.New("Typst MathML variant is invalid")
			}
			attrs = append(attrs, attr)
		case "id", "class", "role", "alt", "title", "width", "height", "aria-label":
			if name == "id" && strings.HasPrefix(attr.Val, "rin-page-") {
				return errors.New("Typst page marker is not a top-level canonical marker")
			}
			attrs = append(attrs, attr)
		case "href":
			if node.Data != "a" || !safeLink(attr.Val) {
				return errors.New("Typst HTML contains an unsafe link")
			}
			attrs = append(attrs, attr)
			internalLink = strings.HasPrefix(attr.Val, "#")
		case "src":
			if node.Data != "img" {
				return errors.New("Typst HTML contains an unexpected resource")
			}
			asset, err := resolveImage(attr.Val, assetHashes, assets)
			if err != nil {
				return err
			}
			attrs = append(attrs, html.Attribute{Key: "src", Val: asset}, html.Attribute{Key: "data-rin-asset-path", Val: asset})
		default:
			return fmt.Errorf("Typst HTML attribute %q is unsupported", name)
		}
	}
	if internalLink {
		found := false
		for index := range attrs {
			if attrs[index].Key == "class" {
				attrs[index].Val += " rin-reader-ref"
				found = true
			}
		}
		if !found {
			attrs = append(attrs, html.Attribute{Key: "class", Val: "rin-reader-ref"})
		}
	}
	node.Attr = attrs
	for child := node.FirstChild; child != nil; child = child.NextSibling {
		if err := sanitizeNode(child, assetHashes, assets); err != nil {
			return err
		}
	}
	return nil
}

func resolveImage(raw string, hashes map[[32]byte]string, assets map[string]Asset) (string, error) {
	const prefix = "data:image/svg+xml;base64,"
	if !strings.HasPrefix(raw, prefix) {
		return "", errors.New("Typst image is not a supported embedded SVG")
	}
	data, err := io.ReadAll(base64.NewDecoder(base64.StdEncoding, strings.NewReader(strings.TrimPrefix(raw, prefix))))
	if err != nil || len(data) == 0 || len(data) > 4<<20 {
		return "", errors.New("Typst embedded image is invalid or too large")
	}
	name := hashes[sha256.Sum256(data)]
	return normalizeImage(data, name, assets)
}

func normalizeImage(data []byte, sourcePath string, assets map[string]Asset) (string, error) {
	normalized, err := renderstorage.NormalizeSVGObject(data)
	if err != nil {
		return "", fmt.Errorf("Typst SVG is unsafe: %w", err)
	}
	generatedPath := "typst-assets/" + normalized.Hash + ".svg"
	assets[generatedPath] = Asset{Path: generatedPath, SourcePath: sourcePath, Body: normalized.Bytes}
	return generatedPath, nil
}

func safeLink(raw string) bool {
	if strings.HasPrefix(raw, "#") {
		return len(raw) > 1 && !strings.ContainsAny(raw, "\x00\r\n<> ")
	}
	parsed, err := url.Parse(raw)
	return err == nil && (((parsed.Scheme == "https" || parsed.Scheme == "http") && parsed.Host != "" && parsed.User == nil) || (parsed.Scheme == "mailto" && parsed.Opaque != ""))
}

func allowedElement(tag string) bool {
	switch tag {
	case "article", "section", "div", "p", "span", "h1", "h2", "h3", "h4", "h5", "h6", "a", "em", "strong", "b", "i", "u", "s", "br", "sup", "sub", "blockquote", "pre", "code", "ul", "ol", "li", "table", "thead", "tbody", "tfoot", "tr", "th", "td", "caption", "figure", "figcaption", "img", "hr", "math", "mrow", "mi", "mn", "mo", "ms", "mspace", "mtext", "mfrac", "msqrt", "mroot", "msub", "msup", "msubsup", "munder", "mover", "munderover", "mtable", "mtr", "mtd", "semantics", "annotation":
		return true
	}
	return false
}

func findElement(node *html.Node, name string) *html.Node {
	if node.Type == html.ElementNode && node.Data == name {
		return node
	}
	for child := node.FirstChild; child != nil; child = child.NextSibling {
		if found := findElement(child, name); found != nil {
			return found
		}
	}
	return nil
}

func isHeading(tag string) bool {
	return len(tag) == 2 && tag[0] == 'h' && tag[1] >= '1' && tag[1] <= '6'
}

func textContent(node *html.Node) string {
	if node.Type == html.TextNode {
		return node.Data
	}
	var out strings.Builder
	for child := node.FirstChild; child != nil; child = child.NextSibling {
		out.WriteString(textContent(child))
	}
	return out.String()
}

func assetKeys(values map[string]Asset) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}
